version: '3.6'

services:

  nestjs_service_1:
    container_name: nestjs_service_1
    image: ssanchez11/shopaholic_api_service:0.0.1
    restart: always
    deploy:
      resources:
        limits:
          memory: 500M
    ports:
      - 3000:3000

