version: "3.6"

# Service templates

x-mariadb-defaults: &mariadb-service
  build:
    context: ./graceful_shutdown_mariadb
  env_file:
    - ./.env
  environment:
    - MARIADB_USER=${MARIADB_USER}
    - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    - MARIADB_DATABASE=${MARIADB_DATABASE}
    - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
  networks:
    - galera-ha-stack

x-haproxy-defaults: &haproxy-service
  image: "haproxytech/haproxy-alpine:2.7"
  depends_on:
    - mariadb_slave_1
    - mariadb_slave_2
    - mariadb_slave_3
    - mariadb_master_1
    - mariadb_master_2
    - mariadb_master_3
  links:
    - mariadb_slave_1
    - mariadb_slave_2
    - mariadb_slave_3
    - mariadb_master_1
    - mariadb_master_2
    - mariadb_master_3
  volumes:
    - ./haproxy:/usr/local/etc/haproxy:ro


networks:
  galera-ha-stack:
    ipam:
      config:
        - subnet: 172.20.0.0/24


## MariaDB Galera Cluster, a type of MySQL cluster, with HAproxy
## multi-primary MySQL Cluster, in the form of MariaDB Galera Cluster, to make it more reliable to load balance databases.
services:

  # MariaDB Image
  # MariaDB is a community-developed fork of MySQL intended to remain free under the GNU GPL.
  mariadb_master_1:
    <<: *mariadb-service
    container_name: mariadb_master_1
    volumes:
      - ./mariadb_master_1/db.cnf:/etc/mysql/mariadb.conf.d/db.cnf
      - ./mariadb_master_1/entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql

  # MariaDB Image
  # MariaDB is a community-developed fork of MySQL intended to remain free under the GNU GPL.
  mariadb_master_2:
    <<: *mariadb-service
    container_name: mariadb_master_2
    volumes:
      - ./mariadb_master_2/db.cnf:/etc/mysql/mariadb.conf.d/db.cnf
      - ./mariadb_master_2/entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./start_master_replicant.sh:/start_master_replicant.sh
    depends_on:
      - mariadb_master_1
    command: sh /start_master_replicant.sh
    links:
      - mariadb_master_1

  # MariaDB Image
  # MariaDB is a community-developed fork of MySQL intended to remain free under the GNU GPL.
  mariadb_master_3:
    <<: *mariadb-service
    container_name: mariadb_master_3
    volumes:
      - ./mariadb_master_3/db.cnf:/etc/mysql/mariadb.conf.d/db.cnf
      - ./mariadb_master_3/entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./start_master_replicant.sh:/start_master_replicant.sh
    depends_on:
      - mariadb_master_2
    command: sh /start_master_replicant.sh
    links:
      - mariadb_master_2

  # MariaDB Image
  # MariaDB is a community-developed fork of MySQL intended to remain free under the GNU GPL.
  mariadb_slave_1:
    <<: *mariadb-service
    container_name: mariadb_slave_1
    volumes:
      - ./mariadb_slave_1/db.cnf:/etc/mysql/mariadb.conf.d/db.cnf
      - ./mariadb_slave_1/entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./configure_slave.sh:/usr/bin/configure_slave.sh
      - ./start_master_slave.sh:/docker-entrypoint-initdb.d/start_master_slave.sh
    depends_on:
      - mariadb_master_1
      - mariadb_master_2
      - mariadb_master_3
    links:
      - mariadb_master_1
      - mariadb_master_2
      - mariadb_master_3

  # MariaDB Image
  # MariaDB is a community-developed fork of MySQL intended to remain free under the GNU GPL.
  mariadb_slave_2:
    <<: *mariadb-service
    container_name: mariadb_slave_2
    volumes:
      - ./mariadb_slave_2/db.cnf:/etc/mysql/mariadb.conf.d/db.cnf
      - ./mariadb_slave_2/entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./start_master_slave.sh:/docker-entrypoint-initdb.d/start_slave.sh
    depends_on:
      - mariadb_slave_1
      - mariadb_master_1
      - mariadb_master_2
      - mariadb_master_3
    links:
      - mariadb_slave_1
      - mariadb_master_1
      - mariadb_master_2
      - mariadb_master_3

  # MariaDB Image
  # MariaDB is a community-developed fork of MySQL intended to remain free under the GNU GPL.
  mariadb_slave_3:
    <<: *mariadb-service
    container_name: mariadb_slave_3
    volumes:
      - ./mariadb_slave_3/db.cnf:/etc/mysql/mariadb.conf.d/db.cnf
      - ./mariadb_slave_3/entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./start_master_slave.sh:/docker-entrypoint-initdb.d/start_slave.sh
    depends_on:
      - mariadb_slave_1
      - mariadb_slave_2
      - mariadb_master_1
      - mariadb_master_2
      - mariadb_master_3
    links:
      - mariadb_slave_1
      - mariadb_slave_2
      - mariadb_master_1
      - mariadb_master_2
      - mariadb_master_3


  keepalived-a:
    build:
      context: ./keepalived/proxy-a
    networks:
      galera-ha-stack:
        ipv4_address: 172.20.0.10
    cap_add: 
        - NET_ADMIN

  keepalived-b:
    build:
      context: ./keepalived/proxy-b
    networks:
      galera-ha-stack:
        ipv4_address: 172.20.0.20
    cap_add: 
        - NET_ADMIN


  mariadb_haproxy_1:
    <<: *haproxy-service
    container_name: mariadb_haproxy_1
    networks:
      galera-ha-stack:
        ipv4_address: 172.20.0.50
        aliases:
          - haproxy-a.ha.stack


  mariadb_haproxy_2:
    <<: *haproxy-service
    container_name: mariadb_haproxy_2
    networks:
      galera-ha-stack:
        ipv4_address: 172.20.0.60
        aliases:
          - haproxy-b.ha.stack

  # php My Admin
  mariadb_web_admin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mariadb_haproxy_1
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_PORT: ${PMA_PORT}
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    links:
      - mariadb_haproxy_1
    ports:
      - "8081:80"
    networks:
      - galera-ha-stack
